### PR TITLE
Fix eslint errors

### PR DESCRIPTION
**Pull request by glennreyes**
- Fixes eslint errors on top of #723.
- Ran [PureComponent codemod](https://github.com/reactjs/react-codemod#pure-component)
- Cleaned up some decorators and moved them to HOC

### CODE REVIEW

**Comment by nikgraf** [comment]
@glennreyes please make a separate PR for each of these changes in the future. It's hard to review such amount of changes.

I suggest we cut a release first and then merge this PR. This PR could have performance implications since a stateless function component and PureComponent are not the same.
What do you think @AleshaOleg?

**Comment by glennreyes** [comment]
@nikgraf good point! I would propose to drop or move the PureComponent codemod commit in this PR and find an alternative way to satisfy its linting errors.

**Comment by AleshaOleg** [comment]
Ups, sorry. Deleted `run-prettier` branch because so some reason in [branches](https://github.com/ubergrape/grape-web-client/branches) page it was marked as `merged`. @glennreyes if you have this branch locally, please push it. If not, I will do changes which you did and will create a new PR.

**Comment by AleshaOleg** [comment]
@nikgraf yes, let's do like we did with `prettier`. Let's wait till release, then merge this changes.

**Pull request closed without merging**
