### PR TITLE
Fixed generating links for messages, sidebar links and other autogene…

### PR DESCRIPTION
**Pull request by AleshaOleg**
…rated links

### CODE REVIEW

**Comment by nikgraf** [comment]
any ideas why it happened in the first place? was it always the case?

**Comment by nikgraf** [comment]
ohhhh, did you test this in Electron? That could be the reason why it existed!

**Comment by AleshaOleg** [comment]
@nikgraf no, I don't know why it's started to appear. But if look closer to [Link](https://github.com/ReactTraining/react-router/blob/master/packages/react-router-dom/modules/Link.js#L69) from react-router-dom - I understand why it's working now with an additional `location.origin` before link. The question is, how it's worked before? Because react-router didn't receive any updates for a long time.

Yes, I tested on electron - all links working fine, even those links which should open in a new window (settings wheel -> account settings, but I didn't change behavior for this link, but I checked them).
We have a special handler for links and how they will be opened. Here: https://github.com/ubergrape/grape-web/blob/master/src/x-platform/open-url/index.js

But it's what happened after users click on the link, and this fix implements how the link will be rendered. To handle properly click, we need render it properly :D

**Comment by nikgraf** [comment]
I think the switch to yarn could have caused it. A couple of hard-locked dependencies were upgraded by that change.

**Comment by AleshaOleg** [comment]
@nikgraf yesterday tried `1.8.1` version with `npm` packages installing. No luck:( Maybe something important was in `package-lock.json`.

**Pull request merged**
